VIDEO_PATH = "data/videos/parking.mp4"
SPACES_PATH = "data/parking_spaces.json"
MODEL_PATH = "yolo11n.pt"

CONFIDENCE_THRESHOLD = 0.50

HISTORY_LENGTH = 8
OCCUPIED_THRESHOLD = 5

SHOW_VEHICLES = False

DATABASE_SAVE_INTERVAL = 10